export const LAND_PROJECTS = [
    {
        id: 'lp-01',
        slug: 'lakeview-enclave-a1',
        title: 'Lakeview Enclave - A1',
        subtitle: 'Premium residential waterfront parcel',
        yearLabel: '2026',
        locationName: 'Purbachal, Dhaka',
        location: { lat: 23.8448, lng: 90.5302 },
        heroImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1400&q=80',
        summary: 'A curated residential land parcel with planned road access, utility lines, and high long-term appreciation potential.',
        metrics: {
            area: '5 Katha',
            type: 'Residential',
            handover: 'Q2 2026',
        },
        ctaHref: '/plots/lakeview-enclave-a1',
    },
    {
        id: 'lp-02',
        slug: 'main-road-business-b7',
        title: 'Main Road Business Plot - B7',
        subtitle: 'Commercial frontage in growth corridor',
        yearLabel: '2026',
        locationName: 'Uttara Sector 16',
        location: { lat: 23.8972, lng: 90.4043 },
        heroImage: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1400&q=80',
        summary: 'Main-road facing commercial land tailored for mixed retail-office development with excellent transport visibility.',
        metrics: {
            area: '6.5 Katha',
            type: 'Commercial',
            handover: 'Q4 2026',
        },
        ctaHref: '/plots/main-road-business-b7',
    },
    {
        id: 'lp-03',
        slug: 'south-facing-c3',
        title: 'South Facing Signature Plot - C3',
        subtitle: 'Documentation-ready premium block',
        yearLabel: 'Now',
        locationName: 'Bashundhara Extension',
        location: { lat: 23.8238, lng: 90.4477 },
        heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1400&q=80',
        summary: 'A rectangular, south-facing plot with immediate transfer readiness and strong neighborhood infrastructure momentum.',
        metrics: {
            area: '5.5 Katha',
            type: 'Residential',
            handover: 'Immediate',
        },
        ctaHref: '/plots/south-facing-c3',
    },
    {
        id: 'lp-04',
        slug: 'corner-premium-d9',
        title: 'Corner Premium Estate - D9',
        subtitle: 'Dual-road access with mixed-use upside',
        yearLabel: '2027',
        locationName: 'Keraniganj New Town',
        location: { lat: 23.7078, lng: 90.3392 },
        heroImage: 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=1400&q=80',
        summary: 'Large corner land with broad frontage and strategic zoning advantages for long-term mixed-use value creation.',
        metrics: {
            area: '8 Katha',
            type: 'Mixed Use',
            handover: 'Q1 2027',
        },
        ctaHref: '/plots/corner-premium-d9',
    },
];
