export const DEFAULT_QR_URL = 'https://portal.pushpodhara.com/unsoldplots';
export const DEFAULT_YOUTUBE_URL = 'https://www.youtube.com/';

export const initialPlotFilters = {
    keyword: '',
    location: 'all',
    propertyType: 'all',
    purpose: 'all',
    amenity: 'all',
};

export const plotsData = [
    {
        id: 1,
        slug: 'business-plot-infinity-loop-a1',
        title: 'Business Plot Infinity Loop - A1',
        categoryLabel: 'Commercial Plot (General)',
        location: 'Purbachal, Dhaka',
        propertyType: 'Commercial',
        purpose: 'Buy',
        katha: '10 Katha',
        benefit: 'Ready utility and expressway access',
        priceLabel: 'BDT 2,100,000.00',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1400&q=80',
        rating: 4.3,
        bedrooms: 0,
        bathrooms: 0,
        squareFeet: 7200,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Main Road Access', 'Electricity', 'Drainage'],
    },
    {
        id: 2,
        slug: 'corner-commercial-park-b7',
        title: 'Corner Commercial Park - B7',
        categoryLabel: 'Commercial Plot (Corner)',
        location: 'Uttara Sector 16',
        propertyType: 'Commercial',
        purpose: 'Investment',
        katha: '12 Katha',
        benefit: 'Dual road frontage and high ROI zone',
        priceLabel: 'BDT 2,300,000.00',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=80',
        rating: 4.6,
        bedrooms: 0,
        bathrooms: 0,
        squareFeet: 8640,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Corner Access', 'Security', 'Water Line'],
    },
    {
        id: 3,
        slug: 'residential-garden-c3',
        title: 'Residential Garden Plot - C3',
        categoryLabel: 'Residential Plot',
        location: 'Bashundhara Extension',
        propertyType: 'Residential',
        purpose: 'Buy',
        katha: '5 Katha',
        benefit: 'School, park and market within walking distance',
        priceLabel: 'BDT 1,650,000.00',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1400&q=80',
        rating: 4.1,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 2400,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Park Nearby', 'Gas Line', 'Community Gate'],
    },
    {
        id: 4,
        slug: 'mixed-use-premium-d9',
        title: 'Mixed Use Premium Plot - D9',
        categoryLabel: 'Mixed Use Plot',
        location: 'Keraniganj New Town',
        propertyType: 'Mixed Use',
        purpose: 'Development',
        katha: '8 Katha',
        benefit: 'Planned transport corridor and future mall zone',
        priceLabel: 'BDT 2,850,000.00',
        image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=1400&q=80',
        rating: 4.7,
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: 3800,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Future Metro Access', 'Wide Roads', 'Drainage'],
    },
    {
        id: 5,
        slug: 'lakeview-residential-e2',
        title: 'Lakeview Residential Plot - E2',
        categoryLabel: 'Residential Plot (Lake View)',
        location: 'Srinagar, Munshiganj',
        propertyType: 'Residential',
        purpose: 'Investment',
        katha: '6 Katha',
        benefit: 'Calm environment with long-term appreciation',
        priceLabel: 'BDT 1,920,000.00',
        image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1400&q=80',
        rating: 4.2,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 2800,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Lake View', 'Security', 'Electricity'],
    },
    {
        id: 6,
        slug: 'city-commercial-hub-f4',
        title: 'City Commercial Hub - F4',
        categoryLabel: 'Commercial Plot (Prime)',
        location: 'Gazipur Chowrasta',
        propertyType: 'Commercial',
        purpose: 'Development',
        katha: '14 Katha',
        benefit: 'Logistics route, utilities and banking support',
        priceLabel: 'BDT 3,120,000.00',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1400&q=80',
        rating: 4.4,
        bedrooms: 0,
        bathrooms: 1,
        squareFeet: 9600,
        detailsHref: '#',
        qrUrl: DEFAULT_QR_URL,
        youtubeUrl: DEFAULT_YOUTUBE_URL,
        amenities: ['Highway Access', 'Banking Support', 'Water Line'],
    },
];
