const AGENTS = {
    anika: {
        name: 'Anika Rahman',
        role: 'Senior Property Consultant',
        phone: '+880 1711-123456',
        email: 'anika@nexthome.com',
        avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&q=80',
    },
    fahim: {
        name: 'Fahim Hassan',
        role: 'Investment Advisor',
        phone: '+880 1811-908070',
        email: 'fahim@nexthome.com',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    },
    tasmia: {
        name: 'Tasmia Kabir',
        role: 'Project Relationship Manager',
        phone: '+880 1911-667788',
        email: 'tasmia@nexthome.com',
        avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80',
    },
};

export const projects = [
    {
        id: '1',
        slug: 'pushpodhara-eco-city',
        title: 'Pushpodhara Eco-City',
        subtitle: 'Master-planned eco township beside Dhaka-Mawa growth corridor.',
        description: 'Master planned eco-township with landscaped roads, community facilities, and long-term growth potential.',
        overview:
            'Pushpodhara Eco-City is designed as a complete land community with balanced green planning, walkable internal roads, and ready utility corridors. The project focuses on long-term value appreciation through planned civic nodes, school frontage, and accessible transit links from the expressway.',
        location: 'Dhaka-Mawa Expressway, Srinagar',
        category: 'eco_city',
        type: 'Residential Community',
        transaction: 'sale',
        status: 'active',
        featured: true,
        bedrooms: 5,
        bathrooms: 4,
        sizeSqft: 2500,
        totalPlots: 120,
        availablePlots: 45,
        priceLabel: 'BDT 5,500,000',
        priceValue: 5500000,
        coordinates: { lat: 23.5412, lng: 90.3647 },
        heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1600&q=80',
            'https://images.unsplash.com/photo-1600566752227-8f3b8c1fd3f4?w=1600&q=80',
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=80',
        ],
        highlights: [
            'Gated eco community planning with controlled access points',
            'Planned utility ducts for water, electricity, and telecom',
            'Dedicated green belts and walkable public spaces',
            'High demand location connected to Dhaka-Mawa Expressway',
        ],
        amenities: ['Central Park', 'Community Mosque', 'Kids Zone', 'Jogging Track', 'Security Surveillance', 'Water Line', 'Drainage', 'Street Lighting'],
        nearbyPlaces: [
            { name: 'Dhaka-Mawa Expressway Interchange', distance: '1.8 km', type: 'Transport' },
            { name: 'Srinagar Model School', distance: '2.6 km', type: 'Education' },
            { name: 'Padma General Hospital', distance: '3.4 km', type: 'Healthcare' },
            { name: 'Srinagar Bazar', distance: '2.1 km', type: 'Retail' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 300,000' },
            { label: 'Down Payment', value: '25% within 45 days' },
            { label: 'Installment Tenure', value: '24 monthly installments' },
            { label: 'Registration Window', value: 'Within 90 days after full payment' },
        ],
        faq: [
            { q: 'Is bank financing available?', a: 'Yes. Partner banks provide land financing for eligible buyers with standard documentation.' },
            { q: 'When can I visit the project site?', a: 'Site visits are available every day from 10 AM to 5 PM with prior appointment.' },
            { q: 'Are utility connections confirmed?', a: 'Primary utility corridors are planned and staged with development milestones.' },
        ],
        agent: AGENTS.anika,
        brochureUrl: '#',
    },
    {
        id: '2',
        slug: 'green-valley-residential',
        title: 'Green Valley Residential',
        subtitle: 'Family-focused low-density plots in Munshiganj growth belt.',
        description: 'Low-density residential plots with utility-ready infrastructure and family-focused amenities.',
        overview:
            'Green Valley Residential emphasizes calm neighborhood living with planned road hierarchy and low-density plot allocation. The project is ideal for primary residences and mid-term investment buyers looking for utility-ready development in a steady appreciation zone.',
        location: 'Srinagar, Munshiganj',
        category: 'residential',
        type: 'Townhouse Block',
        transaction: 'sale',
        status: 'active',
        featured: true,
        bedrooms: 3,
        bathrooms: 2,
        sizeSqft: 1500,
        totalPlots: 80,
        availablePlots: 32,
        priceLabel: 'BDT 2,100,000',
        priceValue: 2100000,
        coordinates: { lat: 23.5385, lng: 90.3794 },
        heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
            'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1600&q=80',
            'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687273-8f7d7df9fce9?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1600&q=80',
        ],
        highlights: [
            'Low-density layout for quieter neighborhood experience',
            'Road and drainage network planned for all blocks',
            'Strong family-oriented project environment',
            'Attractive entry point for first-time land buyers',
        ],
        amenities: ['Community Lawn', 'Internal Road Network', 'Drainage', 'Street Lights', 'Play Area', 'Entry Gate', 'Landscaped Median', 'Visitor Parking'],
        nearbyPlaces: [
            { name: 'Munshiganj Regional Road', distance: '1.4 km', type: 'Transport' },
            { name: 'Green Valley School', distance: '1.9 km', type: 'Education' },
            { name: 'Srinagar Upazila Complex', distance: '2.7 km', type: 'Civic' },
            { name: 'Family Health Center', distance: '2.3 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 150,000' },
            { label: 'Down Payment', value: '20% within 30 days' },
            { label: 'Installment Tenure', value: '30 monthly installments' },
            { label: 'Handover Policy', value: 'Upon full clearance and documentation' },
        ],
        faq: [
            { q: 'Can I buy multiple adjacent plots?', a: 'Yes, adjacent plot requests are supported based on availability at booking time.' },
            { q: 'What are the documentation charges?', a: 'Registration and legal costs follow prevailing government rates and processing fees.' },
            { q: 'Is this suitable for resale investment?', a: 'Yes. The location has steady demand due to road access and planned utilities.' },
        ],
        agent: AGENTS.tasmia,
        brochureUrl: '#',
    },
    {
        id: '3',
        slug: 'commercial-hub-gazipur',
        title: 'Commercial Hub Gazipur',
        subtitle: 'Strategic commercial plots near industrial and transit nodes.',
        description: 'Strategic commercial frontage near industrial zones for retail, office, and mixed business use.',
        overview:
            'Commercial Hub Gazipur is built for business-centric land use, including office frontage, retail bays, and mixed operational units. The project is situated for high visibility with convenient logistics routes, making it attractive for rental-yield and long-term lease portfolios.',
        location: 'Gazipur Chowrasta',
        category: 'commercial',
        type: 'Commercial',
        transaction: 'rent',
        status: 'active',
        featured: false,
        bedrooms: 5,
        bathrooms: 3,
        sizeSqft: 29000,
        totalPlots: 50,
        availablePlots: 18,
        priceLabel: 'BDT 1,200,000 / month',
        priceValue: 1200000,
        coordinates: { lat: 24.0021, lng: 90.4203 },
        heroImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&q=80',
            'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80',
            'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1600&q=80',
            'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1600&q=80',
            'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=1600&q=80',
        ],
        highlights: [
            'High frontage visibility for retail and office use',
            'Close connectivity to Gazipur industrial corridors',
            'Suitable for lease-based recurring income models',
            'Wide access road planning for business traffic',
        ],
        amenities: ['Service Road', 'Commercial Utility Grid', 'Visitor Parking', 'CCTV Network', 'Power Backup Zone', 'Wide Frontage', 'Signage Corridor', '24/7 Security'],
        nearbyPlaces: [
            { name: 'Gazipur Chowrasta', distance: '0.9 km', type: 'Transport' },
            { name: 'Industrial Belt Entrance', distance: '1.5 km', type: 'Business' },
            { name: 'Gazipur District Hospital', distance: '2.8 km', type: 'Healthcare' },
            { name: 'Gazipur Commercial Market', distance: '1.2 km', type: 'Retail' },
        ],
        paymentPlan: [
            { label: 'Booking Deposit', value: 'BDT 500,000' },
            { label: 'Advance Rent', value: '6 months' },
            { label: 'Security Deposit', value: '2 months equivalent' },
            { label: 'Lease Term', value: 'Minimum 3 years' },
        ],
        faq: [
            { q: 'Is this project only for rent?', a: 'Primary offering is rental and long-term lease arrangements for commercial occupants.' },
            { q: 'Can brands customize frontage?', a: 'Yes, branding and facade standards are available under project guidelines.' },
            { q: 'What is the expected footfall profile?', a: 'The location benefits from industrial worker, logistics, and commuter movement.' },
        ],
        agent: AGENTS.fahim,
        brochureUrl: '#',
    },
    {
        id: '4',
        slug: 'riverside-retreat',
        title: 'Riverside Retreat',
        subtitle: 'Curated riverfront residential enclave with premium walkways.',
        description: 'Scenic residential enclave near riverfront corridors with curated green spaces and walking zones.',
        overview:
            'Riverside Retreat offers a calm premium living setting near the Padma corridor, combining open green surfaces and thoughtful private-community zoning. The project suits villa-home seekers and investors targeting scenic, low-density residential value.',
        location: 'Padma Bridge Area',
        category: 'residential',
        type: 'Villa Plots',
        transaction: 'sale',
        status: 'active',
        featured: true,
        bedrooms: 5,
        bathrooms: 6,
        sizeSqft: 1900,
        totalPlots: 60,
        availablePlots: 42,
        priceLabel: 'BDT 7,700,000',
        priceValue: 7700000,
        coordinates: { lat: 23.4462, lng: 90.2462 },
        heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80',
            'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=1600&q=80',
            'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1600&q=80',
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=80',
        ],
        highlights: [
            'River-adjacent atmosphere with high lifestyle appeal',
            'Premium villa-oriented block planning',
            'Strong leisure and second-home buyer potential',
            'Direct access to evolving bridge-area developments',
        ],
        amenities: ['Riverside Promenade', 'Landscaped Green Deck', 'Clubhouse Zone', 'Jogging Loop', 'Security Gate', 'Smart Street Lights', 'Water Reservoir', 'Community Plaza'],
        nearbyPlaces: [
            { name: 'Padma Bridge Link Road', distance: '1.3 km', type: 'Transport' },
            { name: 'Riverside Community School', distance: '2.2 km', type: 'Education' },
            { name: 'Bridge Point Market', distance: '2.0 km', type: 'Retail' },
            { name: 'Padma Regional Clinic', distance: '3.1 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 350,000' },
            { label: 'Down Payment', value: '30% within 60 days' },
            { label: 'Installment Tenure', value: '18 monthly installments' },
            { label: 'Preferred Transfer', value: 'Priority support for legal transfer' },
        ],
        faq: [
            { q: 'Is this suitable for villa construction?', a: 'Yes, the plot planning and front-road ratios are optimized for villa builds.' },
            { q: 'Can I reserve corner plots?', a: 'Corner plot booking is available based on current inventory and payment completion.' },
            { q: 'How close is the site to major roads?', a: 'The project is a short drive from Padma Bridge-linked transport routes.' },
        ],
        agent: AGENTS.anika,
        brochureUrl: '#',
    },
    {
        id: '5',
        slug: 'urban-edge-mixed-use',
        title: 'Urban Edge Mixed-Use',
        subtitle: 'Urban mixed-use cluster for retail and residential demand.',
        description: 'Hybrid development designed for retail and residential units in one high-demand urban cluster.',
        overview:
            'Urban Edge Mixed-Use combines income-ready commercial frontage with residential depth planning in a single integrated footprint. It is built for buyers who want blended use cases, balancing recurring rental potential and high-demand urban ownership.',
        location: 'Uttara Sector 14',
        category: 'mixed_use',
        type: 'Mixed Use',
        transaction: 'sale',
        status: 'booked',
        featured: false,
        bedrooms: 4,
        bathrooms: 4,
        sizeSqft: 2200,
        totalPlots: 40,
        availablePlots: 8,
        priceLabel: 'BDT 10,000,000',
        priceValue: 10000000,
        coordinates: { lat: 23.8685, lng: 90.4012 },
        heroImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80',
            'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb3?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=1600&q=80',
        ],
        highlights: [
            'Mixed-use planning for diversified return potential',
            'Prime Uttara catchment with high urban demand',
            'Optimized frontage for ground-floor retail use',
            'Limited inventory for scarcity-driven value',
        ],
        amenities: ['Mixed Use Corridor', 'Visitor Parking Bay', 'Retail Front Blocks', 'Community Access Lanes', 'CCTV', 'Power Backup Provision', 'Fire Safety Zone', 'Smart Entry'],
        nearbyPlaces: [
            { name: 'Uttara Sector 14 Main Road', distance: '0.7 km', type: 'Transport' },
            { name: 'North City School', distance: '1.6 km', type: 'Education' },
            { name: 'Uttara Shopping Complex', distance: '1.3 km', type: 'Retail' },
            { name: 'Uttara Care Hospital', distance: '2.4 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 600,000' },
            { label: 'Down Payment', value: '35% within 45 days' },
            { label: 'Installment Tenure', value: '12 monthly installments' },
            { label: 'Registration', value: 'Post full payment clearance' },
        ],
        faq: [
            { q: 'Why is availability low?', a: 'This project has high demand and limited plots, with most inventory already booked.' },
            { q: 'Can I use it for both residence and business?', a: 'Yes, selected blocks support mixed-use compatibility as per plan.' },
            { q: 'Is this good for immediate rental yield?', a: 'The location profile supports strong demand from both retail and residents.' },
        ],
        agent: AGENTS.fahim,
        brochureUrl: '#',
    },
    {
        id: '6',
        slug: 'heritage-gardens',
        title: 'Heritage Gardens',
        subtitle: 'Nature-connected single-home community with strong road links.',
        description: 'Nature-connected community blocks with broad roads, lakeside landscaping, and future civic hubs.',
        overview:
            'Heritage Gardens is planned for families seeking a balanced, green-first residential environment without compromising on road connectivity. The community design prioritizes wide streets, utility reliability, and future civic support infrastructure.',
        location: 'Keraniganj',
        category: 'residential',
        type: 'Single Homes',
        transaction: 'rent',
        status: 'active',
        featured: false,
        bedrooms: 4,
        bathrooms: 3,
        sizeSqft: 2100,
        totalPlots: 100,
        availablePlots: 68,
        priceLabel: 'BDT 95,000 / month',
        priceValue: 95000,
        coordinates: { lat: 23.7029, lng: 90.3554 },
        heroImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb3?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687126-df891603c7d6?w=1600&q=80',
            'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=1600&q=80',
        ],
        highlights: [
            'Lake-adjacent neighborhood style planning',
            'Wide internal roads and clean zoning',
            'Large inventory for flexible selection',
            'Rental-friendly project structure',
        ],
        amenities: ['Lakeside Viewpoint', 'Play Lawn', 'Mosque', 'Road Lighting', 'Drainage', 'Security Patrol', 'Water Supply', 'Community Hall'],
        nearbyPlaces: [
            { name: 'Keraniganj Link Road', distance: '1.1 km', type: 'Transport' },
            { name: 'Heritage Public School', distance: '2.3 km', type: 'Education' },
            { name: 'Keraniganj Bazar', distance: '2.0 km', type: 'Retail' },
            { name: 'Unity Medical Center', distance: '2.9 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Deposit', value: 'BDT 120,000' },
            { label: 'Advance Rent', value: '3 months' },
            { label: 'Security Deposit', value: '2 months equivalent' },
            { label: 'Lease Flexibility', value: '12-24 month terms' },
        ],
        faq: [
            { q: 'Is this project ready for occupancy?', a: 'Yes, selected blocks are ready and utilities are operational in active zones.' },
            { q: 'Are furnished options available?', a: 'Furnished and semi-furnished options can be arranged on request.' },
            { q: 'Can families schedule evening visits?', a: 'Yes, evening slots are available with prior booking confirmation.' },
        ],
        agent: AGENTS.tasmia,
        brochureUrl: '#',
    },
    {
        id: '7',
        slug: 'lakeview-signature',
        title: 'Lakeview Signature',
        subtitle: 'Premium upscale villa plots with lake-facing frontages.',
        description: 'Premium lake-facing land parcels for upscale residences and investment-grade resale value.',
        overview:
            'Lakeview Signature targets premium buyers seeking visual frontage, exclusivity, and superior long-term appreciation potential. The project has controlled inventory and a high-spec neighborhood concept aimed at luxury residential development.',
        location: 'Purbachal',
        category: 'residential',
        type: 'Luxury Villa',
        transaction: 'sale',
        status: 'upcoming',
        featured: true,
        bedrooms: 6,
        bathrooms: 5,
        sizeSqft: 3100,
        totalPlots: 35,
        availablePlots: 22,
        priceLabel: 'BDT 12,500,000',
        priceValue: 12500000,
        coordinates: { lat: 23.8397, lng: 90.5389 },
        heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687273-8f7d7df9fce9?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80',
            'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1600&q=80',
            'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=1600&q=80',
        ],
        highlights: [
            'Premium lake-facing plot orientation',
            'Low inventory upscale neighborhood positioning',
            'Strong resale potential in Purbachal belt',
            'High-end villa architecture compatibility',
        ],
        amenities: ['Private Club Lounge', 'Lakeside Walkway', 'Premium Security Layer', 'Landscaped Boulevard', 'High Mast Lighting', 'Smart Utility Ducts', 'Concierge Desk', 'Private Event Lawn'],
        nearbyPlaces: [
            { name: 'Purbachal Highway Connector', distance: '1.0 km', type: 'Transport' },
            { name: 'Lakeview International School', distance: '2.2 km', type: 'Education' },
            { name: 'Purbachal Lifestyle Mall', distance: '2.9 km', type: 'Retail' },
            { name: 'Specialized Health Point', distance: '3.3 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 750,000' },
            { label: 'Down Payment', value: '35% within 30 days' },
            { label: 'Installment Tenure', value: '15 monthly installments' },
            { label: 'Priority Allocation', value: 'Early-bird block preference' },
        ],
        faq: [
            { q: 'When is this project launching?', a: 'The project is in upcoming phase with priority booking now open.' },
            { q: 'Can I reserve lake-facing corners?', a: 'Priority buyers can request premium-facing blocks based on queue position.' },
            { q: 'Is this suitable for long-term luxury investment?', a: 'Yes, it is positioned for premium end-user and resale demand.' },
        ],
        agent: AGENTS.anika,
        brochureUrl: '#',
    },
    {
        id: '8',
        slug: 'northgate-commerce',
        title: 'Northgate Commerce',
        subtitle: 'Office and retail-ready commercial grid with highway access.',
        description: 'Office-ready commercial grid with direct highway connectivity and utility-prepared lots.',
        overview:
            'Northgate Commerce is an office and retail-centered commercial land development optimized for operational readiness. With direct transport links and utility-first planning, it supports scalable business occupancy and yield-focused acquisition.',
        location: 'Tongi, Gazipur',
        category: 'commercial',
        type: 'Office & Retail',
        transaction: 'sale',
        status: 'active',
        featured: false,
        bedrooms: 3,
        bathrooms: 3,
        sizeSqft: 2500,
        totalPlots: 52,
        availablePlots: 20,
        priceLabel: 'BDT 6,200,000',
        priceValue: 6200000,
        coordinates: { lat: 23.8926, lng: 90.4056 },
        heroImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80',
        galleryImages: [
            'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80',
            'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1600&q=80',
            'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1600&q=80',
            'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=1600&q=80',
            'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1600&q=80',
        ],
        highlights: [
            'Direct highway linkage for business mobility',
            'Office-ready utility and parking planning',
            'Balanced mix of retail and workspace potential',
            'Location aligned with Tongi industrial activity',
        ],
        amenities: ['Business Plaza Entry', 'Dedicated Parking', 'Utility Grid', 'Service Lifts Zone', 'CCTV', 'Access Control', 'Power Backup', 'Wide Road Front'],
        nearbyPlaces: [
            { name: 'Tongi Highway Link', distance: '0.8 km', type: 'Transport' },
            { name: 'Northgate Technical Institute', distance: '1.9 km', type: 'Education' },
            { name: 'Commerce Square Market', distance: '1.6 km', type: 'Retail' },
            { name: 'Tongi City Medical', distance: '2.7 km', type: 'Healthcare' },
        ],
        paymentPlan: [
            { label: 'Booking Money', value: 'BDT 400,000' },
            { label: 'Down Payment', value: '30% within 45 days' },
            { label: 'Installment Tenure', value: '18 monthly installments' },
            { label: 'Transfer Support', value: 'Legal handover assistance included' },
        ],
        faq: [
            { q: 'Can small businesses purchase here?', a: 'Yes, multiple block options support both SME and larger commercial buyers.' },
            { q: 'Is parking included in planning?', a: 'Yes, designated visitor and owner parking zones are part of the layout.' },
            { q: 'What is the construction timeline?', a: 'Commercial development phases are aligned with utility readiness milestones.' },
        ],
        agent: AGENTS.fahim,
        brochureUrl: '#',
    },
];

export const categoryMeta = [
    { id: 'all', label: 'All Types', icon: 'Layers3' },
    { id: 'residential', label: 'Residential', icon: 'House' },
    { id: 'commercial', label: 'Commercial', icon: 'Building2' },
    { id: 'eco_city', label: 'Eco City', icon: 'Trees' },
    { id: 'mixed_use', label: 'Mixed Use', icon: 'Landmark' },
];

export const statusLabels = {
    active: 'Active',
    upcoming: 'Upcoming',
    booked: 'Booked',
};

export const statusClass = {
    active: 'bg-[#1f7a6d] text-white',
    upcoming: 'bg-[#c99855] text-white',
    booked: 'bg-[#1a1a1a] text-white',
};

export const transactionLabels = {
    sale: 'For Sale',
    rent: 'For Rent',
};

export const cardMotion = {
    hidden: { opacity: 0, y: 22 },
    show: { opacity: 1, y: 0 },
};

export function getProjectBySlug(slug) {
    return projects.find((project) => project.slug === slug) || null;
}

export function getRelatedProjects(currentSlug, limit = 3) {
    const currentProject = getProjectBySlug(currentSlug);
    if (!currentProject) return projects.slice(0, limit);

    const sameCategory = projects.filter(
        (project) => project.slug !== currentSlug && project.category === currentProject.category
    );
    const fallback = projects.filter((project) => project.slug !== currentSlug && project.category !== currentProject.category);

    return [...sameCategory, ...fallback].slice(0, limit);
}
